apps/tag/urls.py
from django.urls import path

from . import views

app_name = 'tag'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list', views.get_queryset_tag, name='tags'),
    path('create', views.CreateView.as_view(), name='create'),
    path('categoria', views.IndexViewCategoria.as_view(), name='index_categoria'),
    path('categoria/create', views.CreateViewCategoria.as_view(), name='create_categoria'),

]

socialbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("", include("apps.authentication.urls")),

    path('instagram/', include('apps.instagram.urls')),
    path('tag/', include('apps.tag.urls')),
    path("", include("apps.home.urls"))

]

apps/templates/categoria/create.html
<div class="card-body">

    <form id="create" action="{% url 'tag:create_categoria' %}" method="post">{% csrf_token %}

        <div class="row">

            <div class="col-md-3 pr-md-1">
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control" name="nome" placeholder="Insira uma nova categoria"
                           required>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-fill btn-primary">Salvar</button>
            </div>
        </div>
    </form>
</div>

apps/templates/categoria/detail.html
<h1>detalhes {{ pagina.nome }}</h1>
<table>
    <tr>
        {% if pagina.username %}
            <th>Usuário</th>
            <th>Senha</th>
        {% endif %}
    </tr>
    <tr>
        {% if pagina.username %}
            <td>{{ pagina.username }}</td>
            <td>{{ pagina.password }}</td>
        {% endif %}
    </tr>
</table>

apps/templates/categoria/index.html
{% if list_page %}
<div class="card-body">
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <label>Nome</label>
                        </div>
                    </div>
                </div>

        {% for categoria in list_page %}
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <p  class="form-control"
                                 >{{ categoria.nome }}</p>
                        </div>
                    </div>
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <button onclick="editarCategoria()" type="button" class="btn btn-primary" data-toggle="modal" data-target="#editarCategoria">
                                  Editar
                            </button>
                            <div class="modal fade" id="editarCategoria" tabindex="-1" role="dialog" aria-labelledby="editarCategoria" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Editar {{ categoria.nome }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                    <ul id="listTags">

                                    </ul>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    <button type="button" class="btn btn-primary">Salvar mudanças</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}

</div>
{% endif %}