apps/instagram/urls.py
from django.urls import path

from . import views

app_name = 'instagram'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/updated', views.UpdateView.as_view(), name='updated'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create', views.CreateView.as_view(), name='create'),
    path('<int:pk>/delete', views.UpdateViewDelete.as_view(), name='delete'),
    # path('create_form', views.form_cadastrar_pagina(), name='form_cadastrar_pagina'),
    # path('<int:pagina_id>/edit', views.edit, name='edit')
]

socialbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("", include("apps.authentication.urls")),

    path('instagram/', include('apps.instagram.urls')),
    path('tag/', include('apps.tag.urls')),
    path("", include("apps.home.urls"))

]

apps/instagram/models.py
import datetime

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils import timezone


# class Categoria(models.Model):
#     nome = models.CharField(max_length=128, unique=True)
#     tags = ArrayField(ArrayField(models.CharField(max_length=255)))
#
#     def __str__(self):
#         return self.nome
from apps.tag.models import Categoria


class Pagina(models.Model):
    ativo = models.BooleanField(default=True)
    data_criacao = models.DateTimeField(auto_now=True)
    nome = models.CharField(max_length=128)
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('nome', 'user')

    def __str__(self):
        return self.nome

    def data_criacao(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('instagram:index')


class ProcessarBot(models.Model):
    nome = models.CharField(max_length=128, null=True, blank=True)
    pagina = models.ForeignKey(Pagina, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    status = models.CharField(max_length=128, null=True, blank=True)

apps/instagram/forms.py
from datetime import datetime

from django import forms

from apps.instagram.models import Pagina


class PaginaForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")
    username = forms.CharField(widget=forms.TextInput(), label='username')
    password = forms.CharField(widget=forms.TextInput(), label='password')

    class Meta:
        model = Pagina
        fields = ['nome', 'username', 'password']

    def dados(self):
        return {'form': self.cleaned_data, 'data': datetime.now()}

apps/instagram/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib import messages
from apps.instagram.forms import PaginaForm
from apps.instagram.models import Pagina


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'home/instagram.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Pagina.objects.filter(user=self.request.user, ativo=True).order_by('-nome')


@method_decorator(login_required, name='dispatch')
class UpdateView(SuccessMessageMixin,UpdateView):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta alterada com sucesso'

    def get_object(self):
        id = self.kwargs.get('pk')
        return get_object_or_404(Pagina, id=id)

    def put(self, *args, **kwargs):
        if self.form_class.is_valid():
            pagina = self.form_class.save(commit=False)
            pagina.save()
            return render(self.request , reverse_lazy('instagram:index'))
        else:
            return render(self.request, 'instagram.html', {})


@method_decorator(login_required, name='dispatch')
class UpdateViewDelete(DeleteView, SuccessMessageMixin):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta deletada com sucesso'

    def get_object(self):
        id = self.kwargs.get('pk')
        return get_object_or_404(Pagina, id=id)

    def put(self, *args, **kwargs):
        if self.form_class.is_valid():
            pagina = self.form_class.save(commit=False)
            pagina.save()
            return render(self.request, reverse_lazy('instagram:index'))
        else:
            return render(self.request, 'instagram.html', {})


class DetailView(generic.DetailView):
    model = Pagina
    template_name = 'home/instagram.html'


@method_decorator(login_required, name='dispatch')
class CreateView(SuccessMessageMixin, generic.CreateView):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta criada com sucesso'

    def post(self, request, *args, **kwargs):
        user = request.user
        form_class = PaginaForm(request.POST)
        if form_class.is_valid():
            pagina = form_class.save(commit=False)
            pagina.user = user
            pagina.save()
            messages.success(self.request, 'Conta criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('instagram:index'))
        else:
            return HttpResponseRedirect(reverse_lazy('instagram:index'))


# @login_required(login_url="/login/")
# def get_instagram():
#
# def form_cadastrar_pagina(request):
#     form_class = PaginaForm()
#     return render(request, "form.html", {'form': form_class})

def results(request, pagina_id):
    return HttpResponse("Você estava vendo detalhes da pagina %s." % pagina_id)

apps/templates/instagram/create.html
<div class="card-body">

    <form id="create" action="{% url 'instagram:create' %}" method="post">{% csrf_token %}

        <div class="row">

            <div class="col-md-3 pr-md-1">
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control" name="nome" placeholder="Insira um nome para a conta"
                           required>
                </div>
            </div>
            <div class="col-md-3 px-md-1">
                <div class="form-group">
                    <label>Username</label>
                    <input type="text" name="username" class="form-control" required placeholder="usuario" placeholder>
                </div>
            </div>
            <div class="col-md-3 pl-md-1">
                <div class="form-group">
                    <label>Senha</label>
                    <input type="password" name="password" class="form-control" placeholder="Senha" required>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-fill btn-primary">Salvar</button>
            </div>
        </div>
    </form>
</div>

apps/templates/instagram/index.html
{% if list_page %}
<div class="card-body">
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <label>Nome</label>
                        </div>
                    </div>
                    <div class="col-md-3 px-md-1">
                        <div class="form-group">
                            <label>Username</label>
                        </div>
                    </div>
                    <div class="col-md-3 pl-md-1">
                        <div class="form-group">
                            <label>Senha</label>
                        </div>
                    </div>

                </div>

        {% for pagina in list_page %}
            <form id="create" action="{% url 'instagram:updated' pagina.id %}" method="POST">{% csrf_token %}
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <input type="text" class="form-control" name="nome" placeholder="Insira um nome para a conta"
                                   value = {{ pagina.nome }} required>
                        </div>
                    </div>
                    <div class="col-md-3 px-md-1">
                        <div class="form-group">
                            <input type="text" name="username" class="form-control" value = {{ pagina.username }} required placeholder="usuario" placeholder>
                        </div>
                    </div>
                    <div class="col-md-3 pl-md-1">
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" value = {{ pagina.password }} placeholder="Senha" required>
                        </div>
                    </div>
                    <div class="col-md-3 pl-md-1">
                        <div class="form-group">
                            <button type="submit" class="btn btn-fill btn-primary btn-sem-margem">Editar</button>
                        </div>
                    </div>

{#                    <div class="col-md-3 pl-md-1">#}
{#                        <form id="create" action="{% url 'instagram:delete' pagina.id %}" method="POST">{% csrf_token %}#}
{#                            <div class="form-group">#}
{#                                <button type="submit" class="btn btn-fill btn-danger btn-sem-margem" >Excluir</button>#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}

                </div>
            </form>
        {% endfor %}

</div>
{% endif %}