apps/tag/urls.py
from django.urls import path

from . import views

app_name = 'tag'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list', views.get_queryset_tag, name='tags'),
    path('create', views.CreateView.as_view(), name='create'),
    path('categoria', views.IndexViewCategoria.as_view(), name='index_categoria'),
    path('categoria/create', views.CreateViewCategoria.as_view(), name='create_categoria'),

]

socialbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("", include("apps.authentication.urls")),

    path('instagram/', include('apps.instagram.urls')),
    path('tag/', include('apps.tag.urls')),
    path("", include("apps.home.urls"))

]

apps/tag/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Categoria(models.Model):
    nome = models.CharField(max_length=128, unique=True)
    data_criacao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Tag(models.Model):
    nome = models.CharField(max_length=128, unique=True)
    data_criacao = models.DateTimeField(auto_now=True)
    categoria = models.ManyToManyField(Categoria)

    def __str__(self):
        return self.nome

apps/tag/forms.py
from apps.tag.models import Tag, Categoria
from django import forms


class CategoriaForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")

    class Meta:
        model = Categoria
        fields = ['nome']


class TagForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")

    class Meta:
        model = Tag
        fields = ['nome']

apps/tag/views.py
from django.shortcuts import render
import json
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib import messages
from requests import Response

from apps.tag.forms import TagForm, CategoriaForm
from apps.tag.models import Tag, Categoria
from django.template import loader
from django.http import JsonResponse


@method_decorator(login_required, name='dispatch')
class CreateView(SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    template_name = 'home/tag.html'
    success_message = 'Tag criada com sucesso'

    def post(self, request, *args, **kwargs):
        form_class = TagForm(request.POST)
        if form_class.is_valid():
            tag = form_class.save()
            tag.save()
            messages.success(self.request, 'Tag criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('tag:index'))
        else:
            return HttpResponseRedirect(reverse_lazy('tag:index'))


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'home/tag.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Tag.objects.all().order_by('-nome')


@method_decorator(login_required, name='dispatch')
class IndexViewCategoria(generic.ListView):
    template_name = 'home/categoria.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Categoria.objects.all().order_by('-nome')


@method_decorator(login_required, name='dispatch')
class CreateViewCategoria(CreateView, SuccessMessageMixin):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'home/categoria.html'
    success_message = 'Categoria criada com sucesso'

    def post(self, request, *args, **kwargs):
        form_class = CategoriaForm(request.POST)
        if form_class.is_valid():
            tag = form_class.save()
            tag.save()
            messages.success(self.request, 'Categoria criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('tag:index_categoria'))
        else:
            return HttpResponseRedirect(reverse_lazy('tag:index_categoria'))


@login_required(login_url="/login/")
# @method_decorator(login_required, name='dispatch')
def get_queryset_tag(request):
    tag = Tag.objects.all().order_by('nome').values()

    return JsonResponse(list(tag), status=200, content_type="application/json", safe=False)

apps/templates/tag/create.html
<div class="card-body">

    <form id="create" action="{% url 'tag:create' %}" method="post">{% csrf_token %}

        <div class="row">

            <div class="col-md-3 pr-md-1">
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control" name="nome" placeholder="Insira uma nova tag"
                           required>
                </div>
            </div>
{#            <div class="col-md-3 pr-md-1">#}
{#                <div class="form-group">#}
{#                      <label>Categorias</label>#}
{#                    <input type="text" class="form-control" id="inputItemCategoria" name="categoria" placeholder="Insira categorais">#}
{#                    <button type="button" onclick="return addItem('listCategorias')">add</button>#}
{##}
{##}
{#                    <ul id="listCategorias">#}
{##}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
            <div class="card-footer">
                <button type="submit" class="btn btn-fill btn-primary">Salvar</button>
            </div>
        </div>
    </form>
</div>

apps/templates/tag/detail.html
<h1>detalhes {{ pagina.nome }}</h1>
<table>
    <tr>
        {% if pagina.username %}
            <th>Usuário</th>
            <th>Senha</th>
        {% endif %}
    </tr>
    <tr>
        {% if pagina.username %}
            <td>{{ pagina.username }}</td>
            <td>{{ pagina.password }}</td>
        {% endif %}
    </tr>
</table>

apps/templates/tag/index.html
{% if list_page %}
<div class="card-body">
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <label>Nome</label>
                        </div>
                    </div>
                </div>

        {% for tag in list_page %}
                <div class="row">
                    <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                            <input type="text" class="form-control" name="nome" placeholder="Insira um nome para a conta"
                                   value = {{ tag.nome }} required>
                        </div>
                    </div>
                </div>
        {% endfor %}

</div>
{% endif %}