apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path

from apps.home import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

apps/instagram/urls.py
from django.urls import path

from . import views

app_name = 'instagram'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/updated', views.UpdateView.as_view(), name='updated'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create', views.CreateView.as_view(), name='create'),
    path('<int:pk>/delete', views.UpdateViewDelete.as_view(), name='delete'),
    # path('create_form', views.form_cadastrar_pagina(), name='form_cadastrar_pagina'),
    # path('<int:pagina_id>/edit', views.edit, name='edit')
]

apps/tag/urls.py
from django.urls import path

from . import views

app_name = 'tag'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list', views.get_queryset_tag, name='tags'),
    path('create', views.CreateView.as_view(), name='create'),
    path('categoria', views.IndexViewCategoria.as_view(), name='index_categoria'),
    path('categoria/create', views.CreateViewCategoria.as_view(), name='create_categoria'),

]

socialbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("", include("apps.authentication.urls")),

    path('instagram/', include('apps.instagram.urls')),
    path('tag/', include('apps.tag.urls')),
    path("", include("apps.home.urls"))

]

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib.auth.models import User

# Create your models here.

apps/instagram/models.py
import datetime

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils import timezone


# class Categoria(models.Model):
#     nome = models.CharField(max_length=128, unique=True)
#     tags = ArrayField(ArrayField(models.CharField(max_length=255)))
#
#     def __str__(self):
#         return self.nome
from apps.tag.models import Categoria


class Pagina(models.Model):
    ativo = models.BooleanField(default=True)
    data_criacao = models.DateTimeField(auto_now=True)
    nome = models.CharField(max_length=128)
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('nome', 'user')

    def __str__(self):
        return self.nome

    def data_criacao(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('instagram:index')


class ProcessarBot(models.Model):
    nome = models.CharField(max_length=128, null=True, blank=True)
    pagina = models.ForeignKey(Pagina, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    status = models.CharField(max_length=128, null=True, blank=True)

apps/tag/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Categoria(models.Model):
    nome = models.CharField(max_length=128, unique=True)
    data_criacao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Tag(models.Model):
    nome = models.CharField(max_length=128, unique=True)
    data_criacao = models.DateTimeField(auto_now=True)
    categoria = models.ManyToManyField(Categoria)

    def __str__(self):
        return self.nome

apps/instagram/forms.py
from datetime import datetime

from django import forms

from apps.instagram.models import Pagina


class PaginaForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")
    username = forms.CharField(widget=forms.TextInput(), label='username')
    password = forms.CharField(widget=forms.TextInput(), label='password')

    class Meta:
        model = Pagina
        fields = ['nome', 'username', 'password']

    def dados(self):
        return {'form': self.cleaned_data, 'data': datetime.now()}

apps/tag/forms.py
from apps.tag.models import Tag, Categoria
from django import forms


class CategoriaForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")

    class Meta:
        model = Categoria
        fields = ['nome']


class TagForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'required'}), label="nome")

    class Meta:
        model = Tag
        fields = ['nome']

apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse


@login_required(login_url="/login/")
def index(request):
    context = {'segment': 'index'}

    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]
        print(load_template)
        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        if load_template == 'instagram':
            return HttpResponseRedirect(reverse('instagram:index'))

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))

apps/instagram/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib import messages
from apps.instagram.forms import PaginaForm
from apps.instagram.models import Pagina


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'home/instagram.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Pagina.objects.filter(user=self.request.user, ativo=True).order_by('-nome')


@method_decorator(login_required, name='dispatch')
class UpdateView(SuccessMessageMixin,UpdateView):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta alterada com sucesso'

    def get_object(self):
        id = self.kwargs.get('pk')
        return get_object_or_404(Pagina, id=id)

    def put(self, *args, **kwargs):
        if self.form_class.is_valid():
            pagina = self.form_class.save(commit=False)
            pagina.save()
            return render(self.request , reverse_lazy('instagram:index'))
        else:
            return render(self.request, 'instagram.html', {})


@method_decorator(login_required, name='dispatch')
class UpdateViewDelete(DeleteView, SuccessMessageMixin):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta deletada com sucesso'

    def get_object(self):
        id = self.kwargs.get('pk')
        return get_object_or_404(Pagina, id=id)

    def put(self, *args, **kwargs):
        if self.form_class.is_valid():
            pagina = self.form_class.save(commit=False)
            pagina.save()
            return render(self.request, reverse_lazy('instagram:index'))
        else:
            return render(self.request, 'instagram.html', {})


class DetailView(generic.DetailView):
    model = Pagina
    template_name = 'home/instagram.html'


@method_decorator(login_required, name='dispatch')
class CreateView(SuccessMessageMixin, generic.CreateView):
    model = Pagina
    form_class = PaginaForm
    template_name = 'home/instagram.html'
    success_message = 'Conta criada com sucesso'

    def post(self, request, *args, **kwargs):
        user = request.user
        form_class = PaginaForm(request.POST)
        if form_class.is_valid():
            pagina = form_class.save(commit=False)
            pagina.user = user
            pagina.save()
            messages.success(self.request, 'Conta criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('instagram:index'))
        else:
            return HttpResponseRedirect(reverse_lazy('instagram:index'))


# @login_required(login_url="/login/")
# def get_instagram():
#
# def form_cadastrar_pagina(request):
#     form_class = PaginaForm()
#     return render(request, "form.html", {'form': form_class})

def results(request, pagina_id):
    return HttpResponse("Você estava vendo detalhes da pagina %s." % pagina_id)

apps/tag/views.py
from django.shortcuts import render
import json
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib import messages
from requests import Response

from apps.tag.forms import TagForm, CategoriaForm
from apps.tag.models import Tag, Categoria
from django.template import loader
from django.http import JsonResponse


@method_decorator(login_required, name='dispatch')
class CreateView(SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    template_name = 'home/tag.html'
    success_message = 'Tag criada com sucesso'

    def post(self, request, *args, **kwargs):
        form_class = TagForm(request.POST)
        if form_class.is_valid():
            tag = form_class.save()
            tag.save()
            messages.success(self.request, 'Tag criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('tag:index'))
        else:
            return HttpResponseRedirect(reverse_lazy('tag:index'))


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'home/tag.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Tag.objects.all().order_by('-nome')


@method_decorator(login_required, name='dispatch')
class IndexViewCategoria(generic.ListView):
    template_name = 'home/categoria.html'
    context_object_name = 'list_page'

    def get_queryset(self):
        return Categoria.objects.all().order_by('-nome')


@method_decorator(login_required, name='dispatch')
class CreateViewCategoria(CreateView, SuccessMessageMixin):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'home/categoria.html'
    success_message = 'Categoria criada com sucesso'

    def post(self, request, *args, **kwargs):
        form_class = CategoriaForm(request.POST)
        if form_class.is_valid():
            tag = form_class.save()
            tag.save()
            messages.success(self.request, 'Categoria criada com sucesso')
            return HttpResponseRedirect(reverse_lazy('tag:index_categoria'))
        else:
            return HttpResponseRedirect(reverse_lazy('tag:index_categoria'))


@login_required(login_url="/login/")
# @method_decorator(login_required, name='dispatch')
def get_queryset_tag(request):
    tag = Tag.objects.all().order_by('nome').values()

    return JsonResponse(list(tag), status=200, content_type="application/json", safe=False)

apps/templates/home/categoria.html
{% extends "layouts/base.html" %}

{% block title %}  Categorias {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <link href="{{ ASSETS_ROOT }}/css/instagram.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block content %}

    {% if messages %}

                <div class="modal fade show" id="modalMensagem" tabindex="-1" role="dialog" aria-labelledby="modalMensagem" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Notificação</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                       {% for message in messages %}
                            <p{% if message.tags %} class="{{ message.tags }}"{% endif %} >{{ message }} </p>
                            {% endfor %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                      </div>
                    </div>
                  </div>
                </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Nova categoria</h5>
                </div>
                {% include 'categoria/create.html' %}

            </div>
        </div>


        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Lista de categorias</h5>
                </div>
                {% include 'categoria/index.html' %}

            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
    $(document).ready(function() {
    $('#modalMensagem').modal('show');
})

    function addItem(list) {
      const nomeCategoria = document.getElementById('inputItemCategoria').value
      if(nomeCategoria){
          const listaCategorias = document.getElementById(list);
          const listItem = document.createElement("li");
          listItem.innerText = nomeCategoria; // passed the field.
          listaCategorias.appendChild(listItem);
      }
       // stop submission
    }

    function editarCategoria() {
        $.ajax({
        type: "GET",
        url: "{% url 'tag:tags' %}",
        success: function(data){
            console.log(data);
            const listarTags = document.getElementById("listTags");
            console.log(listarTags);
            data.forEach(function(tag){
                console.log(tag);
                const listItem = document.createElement("li");
                listItem.innerText = tag.nome;
                listarTags.appendChild(listItem)
            })
        },
        error: function(response){
            console.log(response);
        }
    })
    }

    </script>
{% endblock javascripts %}

apps/templates/home/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
            <div class="card">

                <form role="form" method="post" action="">

                    <div class="card-header">
                        <h5 class="title">Login</h5>

                        <h6 class="card-category">
                            Adicione suas credenciais
                        </h6>
                    </div>

                    <div class="card-body">

                        <div class="row">

                            <div class="col-md-3 px-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input class="form-control" id="username_login" name="username" required=""
                                           type="text" value="">
                                </div>
                            </div>

                        </div>
                        <div class="row">

                            <div class="col-md-3 px-md-1">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="form-control" id="pwd_login" name="password" required=""
                                           type="password" value="">
                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
                        &nbsp; &nbsp;
                        Ainda não tem uma conta ? <a href="/register.html" class="text-primary">Crie Agora !</a>
                    </div>

                </form>

            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-bot-instagram.html
{% extends "layouts/base.html" %}

{% block title %} Page Bot Instagram {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        <h5 class="title">Instagram</h5>
      </div>
      <div class="card-body">

        <form id="create" action="{% url 'instagram:create' %}" method="post">{% csrf_token %}
          <div class="row">
              <div class="col-md-3 pr-md-1">
              <div class="form-group">
                <label>Nome</label>
                <input type="text" class="form-control" name="nome" placeholder="Insira um nome para a conta" required>
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Username</label>
                <input type="text" name="username" class="form-control" required>
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Senha</label>
                <input type="password" name="password" class="form-control" required>
              </div>
                </div>
             <div class="card-footer">
              <button type="submit" class="btn btn-fill btn-primary">Salvar</button>
            </div>
            </div>
        </form>
      </div>

    </div>
  </div>


  <div class="col-md-4">
    <div class="card card-user">
      <div class="card-body">
        <p class="card-text">
          <div class="author">
            <div class="block block-one"></div>
            <div class="block block-two"></div>
            <div class="block block-three"></div>
            <div class="block block-four"></div>
            <a href="javascript:void(0)">
              <img class="avatar" src="{{ ASSETS_ROOT }}/img/emilyz.jpg" alt="Bill Gates photo - when buys a Linux.">
              <h5 class="title">
                {{ request.user.username }}
              </h5>
            </a>
            <p class="description">
              {{ request.user.email }}
            </p>
          </div>
        </p>
        <div class="card-description">
          Linux, my favorite OS - I admin that windows is just a big mistake.
          Do not be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
        </div>
      </div>
      <div class="card-footer">
        <div class="button-container">
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-facebook">
            <i class="fab fa-facebook"></i>
          </button>
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-twitter">
            <i class="fab fa-twitter"></i>
          </button>
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-google">
            <i class="fab fa-google-plus"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-user.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Editar Perfil</h5>
                </div>
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-5 pr-md-1">
                                <div class="form-group">
                                    <label>UserID (disabled)</label>
                                    <input type="text" class="form-control" disabled="" value="{{ request.user.id }}">
                                </div>
                            </div>
                            <div class="col-md-3 px-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input type="text" class="form-control" value="{{ request.user.username }}">
                                </div>
                            </div>
                            <div class="col-md-4 pl-md-1">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" class="form-control" value="{{ request.user.email }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input type="text" class="form-control" placeholder="Company" value="Mike">
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Sobrenome</label>
                                    <input type="text" class="form-control" placeholder="Last Name" value="Andrew">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Endereço</label>
                                    <input type="text" class="form-control" placeholder="Home Address"
                                           value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>Cidade</label>
                                    <input type="text" class="form-control" placeholder="City" value="Mike">
                                </div>
                            </div>
                            <div class="col-md-4 px-md-1">
                                <div class="form-group">
                                    <label>Estado</label>
                                    <input type="text" class="form-control" placeholder="Country" value="Andrew">
                                </div>
                            </div>
                            <div class="col-md-4 pl-md-1">
                                <div class="form-group">
                                    <label>CEP</label>
                                    <input type="number" class="form-control" placeholder="ZIP Code">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Sobre mim</label>
                                    <textarea rows="4" cols="80" class="form-control"
                                              placeholder="Here can be your description" value="Mike">Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</textarea>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-fill btn-primary">Salvar</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <p class="card-text">
                    <div class="author">
                        <div class="block block-one"></div>
                        <div class="block block-two"></div>
                        <div class="block block-three"></div>
                        <div class="block block-four"></div>
                        <a href="javascript:void(0)">
                            <img class="avatar" src="{{ ASSETS_ROOT }}/img/emilyz.jpg"
                                 alt="Bill Gates photo - when buys a Linux.">
                            <h5 class="title">
                                {{ request.user.username }}
                            </h5>
                        </a>
                        <p class="description">
                            {{ request.user.email }}
                        </p>
                    </div>
                    </p>
                    <div class="card-description">
                        Linux, my favorite OS - I admin that windows is just a big mistake.
                        Do not be scared of the truth because we need to restart the human foundation in truth And I
                        love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                    </div>
                </div>
                <div class="card-footer">
                    <div class="button-container">
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-facebook">
                            <i class="fab fa-facebook"></i>
                        </button>
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-twitter">
                            <i class="fab fa-twitter"></i>
                        </button>
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-google">
                            <i class="fab fa-google-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}